# -*- coding: utf-8 -*-
"""seasonal_weekday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqqLlS2kvEbh1O8oBqcZ8Mv1EKuy0ydt
"""

#include <Trade/Trade.mqh>
CTrade trade;

input int WEEKDAY = 1;
input int DAYOFMONTH = 1;
input int HOUR = 16;
input double SL = 1.0;
input double TP = 1.0;
input int QUANT = 1;
input double PCT_RANGE = 1.0;

MqlRates bar[];

int OnInit() {
   return(INIT_SUCCEEDED);
}

void OnTick() {
   ArraySetAsSeries(bar, true);
   CopyRates(_Symbol, PERIOD_H1, 0, 3, bar);

   MqlDateTime barTime;
   TimeToStruct(bar[0].time, barTime);

   double prevOpen = bar[1].open;
   double prevClose = bar[1].close;
   double percentChange = MathAbs((prevClose - prevOpen) / prevOpen) * 100;
   double price = NormalizeDouble(bar[0].open, _Digits);

   bool entryCondition = barTime.day_of_week == WEEKDAY && barTime.hour == HOUR;

   if (PositionsTotal() == 0 && entryCondition && SymbolInfoDouble(_Symbol, SYMBOL_ASK) < price){

      double range = bar[1].high - bar[1].low;
      double sl_distance = range * SL;
      double tp_distance = range * TP;

      double sl = NormalizeDouble(price - sl_distance, _Digits);
      double tp = NormalizeDouble(price + tp_distance, _Digits);

      trade.Buy(QUANT, _Symbol, price);

   }

   if (PositionsTotal() > 0 && !entryCondition) {
      trade.PositionClose(_Symbol);
      //Print("Orden de cierre ejecutada.");
   }
}